#1 delete a music by admin
WildCodeSchool/2022-09-PHP-Bordeaux-Project-2-avengers pull request #25
Opened 2022-11-16 15:56 UTC by 2xente

2022-11-16 15:58 UTC, amedric submitted a review, later dismissed

2022-11-16 22:34 UTC, jlbokass requested changes
I saw 2 US : show and delete, please refacto

2022-11-17 15:58 UTC, 2xente commented
Si tu peux accepter la pull request "showOneMusic"  avant celle ci ca devrait etre bon

2022-11-18 12:57 UTC, AnthonyMarche submitted a review, later dismissed

2022-11-18 21:26 UTC, AnthonyMarche approved these changes

2022-11-19 08:44 UTC, jlbokass approved these changes

2022-11-19 08:45 UTC, merged